### ISSUE TITLE
Change maximum upload file size to 10 MB

### ISSUE THREAD

**Issue by warpech** [StarcounterSamples/Images#25] opened 2016-04-16 15:57 UTC
I am playing with using Images with a smartphone. 

It is cool, because a Android and iOS let you shoot picture with camera when you tap on `<input type="file>`. But the camera photos are larger than 1 MB, which is the current size limit of Images.

Ideally, maximum upload file size should be configurable.

**Comment by warpech** [comment] 2016-04-16 16:34
I suppose this requires changing the file upload mechanism to use WebSocket instead of HTTP POST. (presented here: https://github.com/StarcounterSamples/KitchenSink/blob/master/src/KitchenSink/wwwroot/KitchenSink/FileUploadPage.html)

Can you confirm, @miyconst?

Btw. did you ever consider using chunked HTTP (`Content-Range`) uploading instead of WebSocket? http://creativejs.com/tutorials/advanced-uploading-techniques-part-1/

**Comment by miyconst** [comment] 2016-04-16 16:52
Yes. Right now maximum request length is 4mb and everything over should be send over websocket.

Sending chunks over HTTP is a possible solution and I worked on it a bit, but did not finish.

**Comment by aloscha** [comment] 2016-05-02 12:12
Could you @warpech review current task on branch: Change_maximum_file_size_#25

**Comment by warpech** [comment] 2016-05-10 12:06
I just tried to review it but it doesn't work. Tried with current Launcher and Starcounter 2.2.1.2069. Could you please take a look again?

**Comment by aloscha** [comment] 2016-05-10 15:38
Yeah there are problem, that socket return 1006 on close.

**Comment by aloscha** [comment] 2016-05-13 21:14
@warpech that issue is blocked by https://github.com/StarcounterSamples/KitchenSink/issues/38
After that issue will resolve, I could make changes inside that project.

Also maybe I create juicy-socket-filedrop component?

**Comment by aloscha** [comment] 2016-05-15 16:04
@warpech could you review it again (please download latest nightly version). Since issue in KitchenSink is resolved (https://github.com/StarcounterSamples/KitchenSink/issues/38) that also will be fix.

**Comment by warpech** [comment] 2016-05-20 14:44
I just tried Launcher + Products + Images and it doesn't work :(

See the below recording:

![bug](https://cloud.githubusercontent.com/assets/566463/15431425/16c49a2a-1eaa-11e6-99ea-6f63a53acb2a.gif)

**Comment by aloscha** [comment] 2016-05-21 00:09
I think it could be error from SC

**Comment by aloscha** [comment] 2016-05-21 21:43
I've fix that error and merge measter into current branch.

**Comment by aloscha** [comment] 2016-05-21 21:57
I've fixed some bugs, occurs after merged master into current branch.

About @warpech bugs, could you @alemoi look at that bug inside StarCounter. To reproduce that please use:
- https://github.com/StarcounterSamples/Products
- https://github.com/StarcounterSamples/Images/tree/Change_maximum_file_size_%2325
- https://github.com/StarcounterPrefabs/Launcher

**Comment by aloscha** [comment] 2016-05-21 22:18
@warpech I've fix that bug. Unfortunately I forgot that juicy-file-drop occurs in two viewmodels and I only passed sessionId only in images, not in combined apps.

@alemoi I can't get stacktrace, but in that configuration I've get sessionId='undefined' and that gives 1011 error.

**Comment by warpech** [comment] 2016-05-23 13:17
I found some new problem. Using Starcounter 2.2.1.2221

Clicking on the "Clear" button results in an error:

```
"System.ArgumentException: The UNC path should be of the form \\server\share.
   at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.GetFullPathInternal(String path)
   at System.IO.FileInfo.Init(String fileName, Boolean checkHost)
   at Images.IllustrationHelper.DeleteFile(Illustration illustration) in c:\www\StarcounterSamples\Images\src\Images\Helpers\IllustrationHelper.cs:line 59
   at Images.ConceptPage.Handle(Delete action) in c:\www\StarcounterSamples\Images\src\Images\ViewModels\ConceptPage.json.cs:line 49
   at Images.ConceptPage.JsonByExample.Schema.<>c.<.ctor>b__0_7(Json pup, Input`1 input) in c:\www\StarcounterSamples\Images\src\Images\obj\x64\Debug\ViewModels\ConceptPage.json.g.cs:line 0
   at Starcounter.Templates.Property`1.InvokeHandler(Json parent, Input`1 input) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-323\Level1\src\Starcounter.XSON\Templates\Foundation\Property.cs:line 240
   at Starcounter.Templates.Property`1.ProcessInput(Json parent, T value) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-323\Level1\src\Starcounter.XSON\Templates\Foundation\Property.cs:line 262
   at Starcounter.XSON.DefaultPatchHandler.ParseAndProcess(TLong property, Json parent, IntPtr valuePtr, Int32 valueSize) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-323\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\DefaultPatchHandler.cs:line 105
   at Starcounter.Internal.TransactionManager.Scope(TransactionHandle handle, Action action) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-323\Level1\src\Starcounter\TransactionManager.cs:line 454
   at Starcounter.Advanced.XSON.JsonExtension.Scope(Json json, Action action) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-323\Level1\src\Starcounter.XSON\Class Json\JsonExtension.cs:line 34
   at Starcounter.XSON.DefaultPatchHandler.Handle(Json root, JsonPatchOperation patchOp, JsonPointer pointer, IntPtr valuePtr, Int32 valueSize) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-323\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\DefaultPatchHandler.cs:line 37
   at Starcounter.XSON.JsonPatch.Apply(Json root, IntPtr patchArrayPtr, Int32 patchArraySize, Boolean strictPatchRejection) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-323\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\JsonPatch.cs:line 678
   at Starcounter.XSON.JsonPatch.Apply(Json root, Byte[] patchArray, Boolean strictPatchRejection) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-323\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\JsonPatch.cs:line 519
   at Starcounter.Internal.PuppetRestHandler.HandleWebSocketJson(Byte[] bs, WebSocket ws) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-323\Level1\src\Starcounter.Apps.JsonPatch\BuiltInRestHandlers\PuppetRestHandler.cs:line 56
   at Starcounter.Internal.AllWsGroups.RunHandler(UInt16 managedHandlerId, UInt32 groupId, WebSocket ws) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-323\Level1\src\Starcounter.Internal\Http\WsManager.cs:line 289
   at Starcounter.GatewayHandlers.HandleWebSocket(UInt16 managedHandlerId, Byte* rawChunk, BMX_TASK_INFO* taskInfo, Boolean* isHandled) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-323\Level1\src\Starcounter\Apps\GatewayHandlers.cs:line 784
HResult=-2147024809
"
```

Screen:

![bug](https://cloud.githubusercontent.com/assets/566463/15472050/6d1ddf98-20f9-11e6-8387-97a43c43bfe2.gif)

**Comment by warpech** [comment] 2016-05-24 08:44
Works good! Please merge

**Closed** 2016-05-25 09:52 UTC
Labels: enhancement, P/Normal
