### ISSUE TITLE
Images application wants to reload new images for IE and Edge

### ISSUE THREAD

**Issue by ubbeK** [StarcounterSamples/Images#23] opened 2016-04-11 09:02 UTC
The investigation from [Products issue 6](https://github.com/StarcounterSamples/Products/issues/6) led to the conclusion that IE and Edge wants to reload the image when editing a product in Procucts-application.

Reproduction sequence: 

1. Load applications: Launcher + Barcodes + Images + Products
2. Add an image and use it in a product, save
3. Open Products and edit the newly added product -> IE and Edge wants to reload the image from a pop up window.

See https://www.dropbox.com/s/p1wm111wq1h1xom/IE_and_Edge_wantsToOpenFileTwice.mp4?dl=0 for the manual test.

**Comment by miyconst** [comment] 2016-04-11 09:29
Some explanation:

IE and Edge opens open file dialog which is caused by [juicy-filedrop](https://github.com/Juicy/juicy-filedrop). Should be fixed. 

You can record gif images and embed into GtiHub instead of using dropbox for sharing an `mp4`. http://www.cockos.com/licecap/

**Comment by warpech** [comment] 2016-04-20 10:38
Fixed. Actually the problem was in `so-juicy-filedrop` (see the comment in code)

**Closed by warpech** 2016-04-20 10:38 UTC
Labels: bug
